services:
  db:
    container_name: mysql-compose
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
volumes:
  mysql-volume:
